# (PART) STATISTICAL ANALYSIS {-}

# Statistical Tests

## Load libraries and data
```{r}
source("R/common.R")
library(broom)

load("../iMAP-part3/RDataRDS/Rjoined_objects.RData", verbose = T)
```

## Kruskal-Wallis test
Hypothesis:

- Ho: Relative abundance of taxon is the same across the group variable.
- Ha: Not the same

Reducing False Positive

- Pairwise Test
  - Test: Paired samples Wilcoxon test or Wilcoxon signed-rank test.
  - Method: Benjamini-Hochberg (BH).

```{r}
set.seed(110912)

load("../iMAP-part3/RDataRDS/Rjoined_objects.RData", verbose = T)

otu_rel_abund <- mo_Rjoined_object %>% 
  rename(group = isolate) %>% 
  filter(level == "genus_phylo",
         !grepl(".*unassigned.*|.*nclassified.*|.*ncultured.*",taxon)) %>% 
  group_by(sample_id, taxon, group) %>% 
  summarise(rel_abund = 100*sum(rel_abund), .groups = "drop")

taxon_pool <- otu_rel_abund %>%
  group_by(group, taxon) %>%
  summarise(median = median(rel_abund), .groups = "drop") %>%
  group_by(taxon) %>% 
  summarise(pool = max(median) < 1,
            median = max(median),
            .groups = "drop")

## Group data
otu_group_rel_abund <- inner_join(otu_rel_abund, taxon_pool, by = "taxon" ) %>% 
  mutate(taxon = if_else(pool, "Other", as.character(taxon))) %>% 
  group_by(sample_id, group, taxon) %>% 
  summarise(rel_abund = sum(rel_abund), 
            median = max(median),
            .groups = "drop") %>%
  mutate(taxon = factor(taxon),
         taxon = fct_reorder(taxon, median, .desc = F),
         taxon = fct_shift(taxon, n = 0))

group_signif <- otu_group_rel_abund %>% 
  group_by(taxon) %>% 
  nest() %>% 
  mutate(expt_tests = map(.x = data,
                         ~kruskal.test(rel_abund~group, data = .x) %>% 
                           tidy())) %>%
  unnest(expt_tests, names_repair = "unique") %>% 
  mutate(p_adj = p.adjust(p.value, method = "BH")) 

group_signif

saveRDS(group_signif, "RDataRDS/group_signif.rds")
```


## Pairwise sample comparison
```{r}
paired_signif <- readRDS("RDataRDS/group_signif.rds") %>% 
  filter(p.value < 0.25) %>%
  mutate(pairwise_tests = map(.x = data,
                              ~pairwise.wilcox.test(x = .x$rel_abund,
                                                    g = .x$group,
                                                    p.adjust.method = "BH") %>%
                                tidy())) %>%
  unnest(pairwise_tests, names_repair = "unique") %>% 
  select(taxon, group1, group2, p_adj)

paired_signif
```



```{r}
# 
#   mutate(rel_abund = if_else(rel_abund == 0, (2/3)*lod, rel_abund)) %>% 
#   ggplot(aes(y = taxon, x = rel_abund, color = group)) +
#   geom_vline(xintercept = lod, size = 0.1, linetype = 2) +
#   stat_summary(fun.data = median_hilow, geom = "pointrange",
#                fun.args = list(conf.int = 0.5),
#                position = position_dodge(width = 0.6),
#                # show.legend = T
#                ) +
#   coord_trans(x = "log10") +
#   scale_x_continuous(limits = c(NA, 100),
#                      breaks = c(0.1, 1, 10, 100),
#                      labels = c(0.1, 1, 10, 100)) +
#   scale_color_manual(name = NULL,
#                     breaks = c("Buffalo",
#                                "Warthog",
#                                "Wildebeest",
#                                "Zebra"),
#                     labels = c("Buffalo",
#                                "Warthog",
#                                "Wildebeest",
#                                "Zebra"),                   
#                     values = c("blue",
#                                "red",
#                                "green",
#                                "purple")) +
# labs(y = NULL,
#        x = "Relative Abundance (log10)",
#        title = "Point Range at 50th Percentile") +
#   theme_classic() +
#   theme(axis.text.y = element_markdown(angle = 0, hjust = 1, vjust = 1),
#         axis.text.x = element_markdown(),
#         legend.text = element_markdown(),
#         legend.key.size = unit(12, "pt"),
#         legend.background = element_rect(colour = "gray", fill = NA),
#         legend.margin = margin(t = 3, r = 0, b = 3, l = 0))
```


```{r}
```
